apiVersion: v1
kind: Pod
metadata:
  name: proyecto-tolerante
  labels:
    app: proyecto-tolerante
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 8080


